/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface College {
  'id' : bigint,
  'name' : string,
  'collegeType' : CollegeType,
  'avgCutoff' : bigint,
  'establishedYear' : bigint,
  'state' : string,
  'nirfRanking' : bigint,
  'topBranches' : Array<string>,
  'location' : string,
}
export type CollegeType = { 'iit' : null } |
  { 'nit' : null } |
  { 'iiit' : null } |
  { 'privateCollege' : null } |
  { 'deemed' : null };
export type Domain = { 'ai' : null } |
  { 'startup' : null } |
  { 'core' : null } |
  { 'general' : null } |
  { 'robotics' : null } |
  { 'webDev' : null };
export interface EntranceExam {
  'id' : bigint,
  'applicationDeadline' : bigint,
  'conductingBody' : string,
  'websiteUrl' : string,
  'name' : string,
  'description' : string,
  'examDate' : bigint,
  'eligibilityCriteria' : string,
  'examType' : ExamType,
}
export type ExamType = { 'national' : null } |
  { 'university' : null } |
  { 'state' : null };
export interface MentorProfile {
  'id' : bigint,
  'bio' : string,
  'domain' : Domain,
  'yearsExperience' : bigint,
  'name' : string,
  'currentRole' : string,
  'college' : string,
}
export interface Resource {
  'id' : bigint,
  'title' : string,
  'tags' : Array<string>,
  'author' : string,
  'category' : ResourceCategory,
  'contentSummary' : string,
}
export type ResourceCategory = { 'ai' : null } |
  { 'roadmap' : null } |
  { 'finance' : null } |
  { 'startup' : null } |
  { 'skills' : null };
export type StartupStage = { 'idea' : null } |
  { 'launch' : null } |
  { 'scale' : null } |
  { 'build' : null } |
  { 'validation' : null };
export interface StartupTip {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'tags' : Array<string>,
  'stage' : StartupStage,
}
export interface UserProfile {
  'interests' : Array<string>,
  'name' : string,
  'stage' : UserStage,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStage = { 'firstYear' : null } |
  { 'workingProfessional' : null } |
  { 'fourthYear' : null } |
  { 'thirdYear' : null } |
  { 'secondYear' : null } |
  { 'aspirant' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCollege' : ActorMethod<[College], bigint>,
  'addExam' : ActorMethod<[EntranceExam], bigint>,
  'addMentor' : ActorMethod<[MentorProfile], bigint>,
  'addResource' : ActorMethod<[Resource], bigint>,
  'addStartupTip' : ActorMethod<[StartupTip], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCollege' : ActorMethod<[bigint], boolean>,
  'deleteExam' : ActorMethod<[bigint], boolean>,
  'deleteMentor' : ActorMethod<[bigint], boolean>,
  'deleteResource' : ActorMethod<[bigint], boolean>,
  'deleteStartupTip' : ActorMethod<[bigint], boolean>,
  'getAllColleges' : ActorMethod<[], Array<College>>,
  'getAllExams' : ActorMethod<[], Array<EntranceExam>>,
  'getAllMentors' : ActorMethod<[], Array<MentorProfile>>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getAllStartupTips' : ActorMethod<[], Array<StartupTip>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollege' : ActorMethod<[bigint], [] | [College]>,
  'getExam' : ActorMethod<[bigint], [] | [EntranceExam]>,
  'getMentor' : ActorMethod<[bigint], [] | [MentorProfile]>,
  'getMentorsByDomain' : ActorMethod<[Domain], Array<MentorProfile>>,
  'getResource' : ActorMethod<[bigint], [] | [Resource]>,
  'getStartupTip' : ActorMethod<[bigint], [] | [StartupTip]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateCollege' : ActorMethod<[bigint, College], boolean>,
  'updateExam' : ActorMethod<[bigint, EntranceExam], boolean>,
  'updateMentor' : ActorMethod<[bigint, MentorProfile], boolean>,
  'updateResource' : ActorMethod<[bigint, Resource], boolean>,
  'updateStartupTip' : ActorMethod<[bigint, StartupTip], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];