/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CollegeType = IDL.Variant({
  'iit' : IDL.Null,
  'nit' : IDL.Null,
  'iiit' : IDL.Null,
  'privateCollege' : IDL.Null,
  'deemed' : IDL.Null,
});
export const College = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'collegeType' : CollegeType,
  'avgCutoff' : IDL.Nat,
  'establishedYear' : IDL.Nat,
  'state' : IDL.Text,
  'nirfRanking' : IDL.Nat,
  'topBranches' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const ExamType = IDL.Variant({
  'national' : IDL.Null,
  'university' : IDL.Null,
  'state' : IDL.Null,
});
export const EntranceExam = IDL.Record({
  'id' : IDL.Nat,
  'applicationDeadline' : IDL.Int,
  'conductingBody' : IDL.Text,
  'websiteUrl' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'examDate' : IDL.Int,
  'eligibilityCriteria' : IDL.Text,
  'examType' : ExamType,
});
export const Domain = IDL.Variant({
  'ai' : IDL.Null,
  'startup' : IDL.Null,
  'core' : IDL.Null,
  'general' : IDL.Null,
  'robotics' : IDL.Null,
  'webDev' : IDL.Null,
});
export const MentorProfile = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'domain' : Domain,
  'yearsExperience' : IDL.Nat,
  'name' : IDL.Text,
  'currentRole' : IDL.Text,
  'college' : IDL.Text,
});
export const ResourceCategory = IDL.Variant({
  'ai' : IDL.Null,
  'roadmap' : IDL.Null,
  'finance' : IDL.Null,
  'startup' : IDL.Null,
  'skills' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'category' : ResourceCategory,
  'contentSummary' : IDL.Text,
});
export const StartupStage = IDL.Variant({
  'idea' : IDL.Null,
  'launch' : IDL.Null,
  'scale' : IDL.Null,
  'build' : IDL.Null,
  'validation' : IDL.Null,
});
export const StartupTip = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'stage' : StartupStage,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserStage = IDL.Variant({
  'firstYear' : IDL.Null,
  'workingProfessional' : IDL.Null,
  'fourthYear' : IDL.Null,
  'thirdYear' : IDL.Null,
  'secondYear' : IDL.Null,
  'aspirant' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'stage' : UserStage,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCollege' : IDL.Func([College], [IDL.Nat], []),
  'addExam' : IDL.Func([EntranceExam], [IDL.Nat], []),
  'addMentor' : IDL.Func([MentorProfile], [IDL.Nat], []),
  'addResource' : IDL.Func([Resource], [IDL.Nat], []),
  'addStartupTip' : IDL.Func([StartupTip], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCollege' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteExam' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMentor' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteResource' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStartupTip' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
  'getAllExams' : IDL.Func([], [IDL.Vec(EntranceExam)], ['query']),
  'getAllMentors' : IDL.Func([], [IDL.Vec(MentorProfile)], ['query']),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getAllStartupTips' : IDL.Func([], [IDL.Vec(StartupTip)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollege' : IDL.Func([IDL.Nat], [IDL.Opt(College)], ['query']),
  'getExam' : IDL.Func([IDL.Nat], [IDL.Opt(EntranceExam)], ['query']),
  'getMentor' : IDL.Func([IDL.Nat], [IDL.Opt(MentorProfile)], ['query']),
  'getMentorsByDomain' : IDL.Func(
      [Domain],
      [IDL.Vec(MentorProfile)],
      ['query'],
    ),
  'getResource' : IDL.Func([IDL.Nat], [IDL.Opt(Resource)], ['query']),
  'getStartupTip' : IDL.Func([IDL.Nat], [IDL.Opt(StartupTip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateCollege' : IDL.Func([IDL.Nat, College], [IDL.Bool], []),
  'updateExam' : IDL.Func([IDL.Nat, EntranceExam], [IDL.Bool], []),
  'updateMentor' : IDL.Func([IDL.Nat, MentorProfile], [IDL.Bool], []),
  'updateResource' : IDL.Func([IDL.Nat, Resource], [IDL.Bool], []),
  'updateStartupTip' : IDL.Func([IDL.Nat, StartupTip], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CollegeType = IDL.Variant({
    'iit' : IDL.Null,
    'nit' : IDL.Null,
    'iiit' : IDL.Null,
    'privateCollege' : IDL.Null,
    'deemed' : IDL.Null,
  });
  const College = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'collegeType' : CollegeType,
    'avgCutoff' : IDL.Nat,
    'establishedYear' : IDL.Nat,
    'state' : IDL.Text,
    'nirfRanking' : IDL.Nat,
    'topBranches' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const ExamType = IDL.Variant({
    'national' : IDL.Null,
    'university' : IDL.Null,
    'state' : IDL.Null,
  });
  const EntranceExam = IDL.Record({
    'id' : IDL.Nat,
    'applicationDeadline' : IDL.Int,
    'conductingBody' : IDL.Text,
    'websiteUrl' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'examDate' : IDL.Int,
    'eligibilityCriteria' : IDL.Text,
    'examType' : ExamType,
  });
  const Domain = IDL.Variant({
    'ai' : IDL.Null,
    'startup' : IDL.Null,
    'core' : IDL.Null,
    'general' : IDL.Null,
    'robotics' : IDL.Null,
    'webDev' : IDL.Null,
  });
  const MentorProfile = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'domain' : Domain,
    'yearsExperience' : IDL.Nat,
    'name' : IDL.Text,
    'currentRole' : IDL.Text,
    'college' : IDL.Text,
  });
  const ResourceCategory = IDL.Variant({
    'ai' : IDL.Null,
    'roadmap' : IDL.Null,
    'finance' : IDL.Null,
    'startup' : IDL.Null,
    'skills' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'category' : ResourceCategory,
    'contentSummary' : IDL.Text,
  });
  const StartupStage = IDL.Variant({
    'idea' : IDL.Null,
    'launch' : IDL.Null,
    'scale' : IDL.Null,
    'build' : IDL.Null,
    'validation' : IDL.Null,
  });
  const StartupTip = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'stage' : StartupStage,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserStage = IDL.Variant({
    'firstYear' : IDL.Null,
    'workingProfessional' : IDL.Null,
    'fourthYear' : IDL.Null,
    'thirdYear' : IDL.Null,
    'secondYear' : IDL.Null,
    'aspirant' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'stage' : UserStage,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCollege' : IDL.Func([College], [IDL.Nat], []),
    'addExam' : IDL.Func([EntranceExam], [IDL.Nat], []),
    'addMentor' : IDL.Func([MentorProfile], [IDL.Nat], []),
    'addResource' : IDL.Func([Resource], [IDL.Nat], []),
    'addStartupTip' : IDL.Func([StartupTip], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCollege' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteExam' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMentor' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteResource' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStartupTip' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
    'getAllExams' : IDL.Func([], [IDL.Vec(EntranceExam)], ['query']),
    'getAllMentors' : IDL.Func([], [IDL.Vec(MentorProfile)], ['query']),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getAllStartupTips' : IDL.Func([], [IDL.Vec(StartupTip)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollege' : IDL.Func([IDL.Nat], [IDL.Opt(College)], ['query']),
    'getExam' : IDL.Func([IDL.Nat], [IDL.Opt(EntranceExam)], ['query']),
    'getMentor' : IDL.Func([IDL.Nat], [IDL.Opt(MentorProfile)], ['query']),
    'getMentorsByDomain' : IDL.Func(
        [Domain],
        [IDL.Vec(MentorProfile)],
        ['query'],
      ),
    'getResource' : IDL.Func([IDL.Nat], [IDL.Opt(Resource)], ['query']),
    'getStartupTip' : IDL.Func([IDL.Nat], [IDL.Opt(StartupTip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateCollege' : IDL.Func([IDL.Nat, College], [IDL.Bool], []),
    'updateExam' : IDL.Func([IDL.Nat, EntranceExam], [IDL.Bool], []),
    'updateMentor' : IDL.Func([IDL.Nat, MentorProfile], [IDL.Bool], []),
    'updateResource' : IDL.Func([IDL.Nat, Resource], [IDL.Bool], []),
    'updateStartupTip' : IDL.Func([IDL.Nat, StartupTip], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };