/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MentorProfile {
    id: bigint;
    bio: string;
    domain: Domain;
    yearsExperience: bigint;
    name: string;
    currentRole: string;
    college: string;
}
export interface EntranceExam {
    id: bigint;
    applicationDeadline: bigint;
    conductingBody: string;
    websiteUrl: string;
    name: string;
    description: string;
    examDate: bigint;
    eligibilityCriteria: string;
    examType: ExamType;
}
export interface StartupTip {
    id: bigint;
    title: string;
    content: string;
    tags: Array<string>;
    stage: StartupStage;
}
export interface College {
    id: bigint;
    name: string;
    collegeType: CollegeType;
    avgCutoff: bigint;
    establishedYear: bigint;
    state: string;
    nirfRanking: bigint;
    topBranches: Array<string>;
    location: string;
}
export interface Resource {
    id: bigint;
    title: string;
    tags: Array<string>;
    author: string;
    category: ResourceCategory;
    contentSummary: string;
}
export interface UserProfile {
    interests: Array<string>;
    name: string;
    stage: UserStage;
}
export enum CollegeType {
    iit = "iit",
    nit = "nit",
    iiit = "iiit",
    privateCollege = "privateCollege",
    deemed = "deemed"
}
export enum Domain {
    ai = "ai",
    startup = "startup",
    core = "core",
    general = "general",
    robotics = "robotics",
    webDev = "webDev"
}
export enum ExamType {
    national = "national",
    university = "university",
    state = "state"
}
export enum ResourceCategory {
    ai = "ai",
    roadmap = "roadmap",
    finance = "finance",
    startup = "startup",
    skills = "skills"
}
export enum StartupStage {
    idea = "idea",
    launch = "launch",
    scale = "scale",
    build = "build",
    validation = "validation"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStage {
    firstYear = "firstYear",
    workingProfessional = "workingProfessional",
    fourthYear = "fourthYear",
    thirdYear = "thirdYear",
    secondYear = "secondYear",
    aspirant = "aspirant"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCollege(college: College): Promise<bigint>;
    addExam(exam: EntranceExam): Promise<bigint>;
    addMentor(mentor: MentorProfile): Promise<bigint>;
    addResource(resource: Resource): Promise<bigint>;
    addStartupTip(tip: StartupTip): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCollege(id: bigint): Promise<boolean>;
    deleteExam(id: bigint): Promise<boolean>;
    deleteMentor(id: bigint): Promise<boolean>;
    deleteResource(id: bigint): Promise<boolean>;
    deleteStartupTip(id: bigint): Promise<boolean>;
    getAllColleges(): Promise<Array<College>>;
    getAllExams(): Promise<Array<EntranceExam>>;
    getAllMentors(): Promise<Array<MentorProfile>>;
    getAllResources(): Promise<Array<Resource>>;
    getAllStartupTips(): Promise<Array<StartupTip>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCollege(id: bigint): Promise<College | null>;
    getExam(id: bigint): Promise<EntranceExam | null>;
    getMentor(id: bigint): Promise<MentorProfile | null>;
    getMentorsByDomain(domain: Domain): Promise<Array<MentorProfile>>;
    getResource(id: bigint): Promise<Resource | null>;
    getStartupTip(id: bigint): Promise<StartupTip | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedData(): Promise<void>;
    updateCollege(id: bigint, college: College): Promise<boolean>;
    updateExam(id: bigint, exam: EntranceExam): Promise<boolean>;
    updateMentor(id: bigint, mentor: MentorProfile): Promise<boolean>;
    updateResource(id: bigint, resource: Resource): Promise<boolean>;
    updateStartupTip(id: bigint, tip: StartupTip): Promise<boolean>;
}
import type { College as _College, CollegeType as _CollegeType, Domain as _Domain, EntranceExam as _EntranceExam, ExamType as _ExamType, MentorProfile as _MentorProfile, Resource as _Resource, ResourceCategory as _ResourceCategory, StartupStage as _StartupStage, StartupTip as _StartupTip, UserProfile as _UserProfile, UserRole as _UserRole, UserStage as _UserStage } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCollege(arg0: College): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCollege(to_candid_College_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCollege(to_candid_College_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addExam(arg0: EntranceExam): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExam(to_candid_EntranceExam_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExam(to_candid_EntranceExam_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMentor(arg0: MentorProfile): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMentor(to_candid_MentorProfile_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMentor(to_candid_MentorProfile_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addResource(arg0: Resource): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(to_candid_Resource_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(to_candid_Resource_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStartupTip(arg0: StartupTip): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStartupTip(to_candid_StartupTip_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStartupTip(to_candid_StartupTip_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCollege(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollege(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollege(arg0);
            return result;
        }
    }
    async deleteExam(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExam(arg0);
            return result;
        }
    }
    async deleteMentor(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMentor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMentor(arg0);
            return result;
        }
    }
    async deleteResource(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResource(arg0);
            return result;
        }
    }
    async deleteStartupTip(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStartupTip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStartupTip(arg0);
            return result;
        }
    }
    async getAllColleges(): Promise<Array<College>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllColleges();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllColleges();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExams(): Promise<Array<EntranceExam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExams();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExams();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMentors(): Promise<Array<MentorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMentors();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMentors();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResources();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResources();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStartupTips(): Promise<Array<StartupTip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStartupTips();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStartupTips();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollege(arg0: bigint): Promise<College | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollege(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollege(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExam(arg0: bigint): Promise<EntranceExam | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExam(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExam(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMentor(arg0: bigint): Promise<MentorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMentor(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMentor(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMentorsByDomain(arg0: Domain): Promise<Array<MentorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMentorsByDomain(to_candid_Domain_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMentorsByDomain(to_candid_Domain_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResource(arg0: bigint): Promise<Resource | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResource(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResource(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStartupTip(arg0: bigint): Promise<StartupTip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStartupTip(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStartupTip(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async updateCollege(arg0: bigint, arg1: College): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollege(arg0, to_candid_College_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollege(arg0, to_candid_College_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateExam(arg0: bigint, arg1: EntranceExam): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExam(arg0, to_candid_EntranceExam_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExam(arg0, to_candid_EntranceExam_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMentor(arg0: bigint, arg1: MentorProfile): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMentor(arg0, to_candid_MentorProfile_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMentor(arg0, to_candid_MentorProfile_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateResource(arg0: bigint, arg1: Resource): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResource(arg0, to_candid_Resource_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResource(arg0, to_candid_Resource_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStartupTip(arg0: bigint, arg1: StartupTip): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStartupTip(arg0, to_candid_StartupTip_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStartupTip(arg0, to_candid_StartupTip_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CollegeType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollegeType): CollegeType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_College_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _College): College {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Domain_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Domain): Domain {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_EntranceExam_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntranceExam): EntranceExam {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ExamType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExamType): ExamType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_MentorProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MentorProfile): MentorProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceCategory_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceCategory): ResourceCategory {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_StartupStage_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StartupStage): StartupStage {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_StartupTip_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StartupTip): StartupTip {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserStage_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStage): UserStage {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_College]): College | null {
    return value.length === 0 ? null : from_candid_College_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EntranceExam]): EntranceExam | null {
    return value.length === 0 ? null : from_candid_EntranceExam_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MentorProfile]): MentorProfile | null {
    return value.length === 0 ? null : from_candid_MentorProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resource]): Resource | null {
    return value.length === 0 ? null : from_candid_Resource_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StartupTip]): StartupTip | null {
    return value.length === 0 ? null : from_candid_StartupTip_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    collegeType: _CollegeType;
    avgCutoff: bigint;
    establishedYear: bigint;
    state: string;
    nirfRanking: bigint;
    topBranches: Array<string>;
    location: string;
}): {
    id: bigint;
    name: string;
    collegeType: CollegeType;
    avgCutoff: bigint;
    establishedYear: bigint;
    state: string;
    nirfRanking: bigint;
    topBranches: Array<string>;
    location: string;
} {
    return {
        id: value.id,
        name: value.name,
        collegeType: from_candid_CollegeType_n26(_uploadFile, _downloadFile, value.collegeType),
        avgCutoff: value.avgCutoff,
        establishedYear: value.establishedYear,
        state: value.state,
        nirfRanking: value.nirfRanking,
        topBranches: value.topBranches,
        location: value.location
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    applicationDeadline: bigint;
    conductingBody: string;
    websiteUrl: string;
    name: string;
    description: string;
    examDate: bigint;
    eligibilityCriteria: string;
    examType: _ExamType;
}): {
    id: bigint;
    applicationDeadline: bigint;
    conductingBody: string;
    websiteUrl: string;
    name: string;
    description: string;
    examDate: bigint;
    eligibilityCriteria: string;
    examType: ExamType;
} {
    return {
        id: value.id,
        applicationDeadline: value.applicationDeadline,
        conductingBody: value.conductingBody,
        websiteUrl: value.websiteUrl,
        name: value.name,
        description: value.description,
        examDate: value.examDate,
        eligibilityCriteria: value.eligibilityCriteria,
        examType: from_candid_ExamType_n31(_uploadFile, _downloadFile, value.examType)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    domain: _Domain;
    yearsExperience: bigint;
    name: string;
    currentRole: string;
    college: string;
}): {
    id: bigint;
    bio: string;
    domain: Domain;
    yearsExperience: bigint;
    name: string;
    currentRole: string;
    college: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        domain: from_candid_Domain_n36(_uploadFile, _downloadFile, value.domain),
        yearsExperience: value.yearsExperience,
        name: value.name,
        currentRole: value.currentRole,
        college: value.college
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    tags: Array<string>;
    author: string;
    category: _ResourceCategory;
    contentSummary: string;
}): {
    id: bigint;
    title: string;
    tags: Array<string>;
    author: string;
    category: ResourceCategory;
    contentSummary: string;
} {
    return {
        id: value.id,
        title: value.title,
        tags: value.tags,
        author: value.author,
        category: from_candid_ResourceCategory_n41(_uploadFile, _downloadFile, value.category),
        contentSummary: value.contentSummary
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    tags: Array<string>;
    stage: _StartupStage;
}): {
    id: bigint;
    title: string;
    content: string;
    tags: Array<string>;
    stage: StartupStage;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        tags: value.tags,
        stage: from_candid_StartupStage_n46(_uploadFile, _downloadFile, value.stage)
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interests: Array<string>;
    name: string;
    stage: _UserStage;
}): {
    interests: Array<string>;
    name: string;
    stage: UserStage;
} {
    return {
        interests: value.interests,
        name: value.name,
        stage: from_candid_UserStage_n51(_uploadFile, _downloadFile, value.stage)
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    iit: null;
} | {
    nit: null;
} | {
    iiit: null;
} | {
    privateCollege: null;
} | {
    deemed: null;
}): CollegeType {
    return "iit" in value ? CollegeType.iit : "nit" in value ? CollegeType.nit : "iiit" in value ? CollegeType.iiit : "privateCollege" in value ? CollegeType.privateCollege : "deemed" in value ? CollegeType.deemed : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    national: null;
} | {
    university: null;
} | {
    state: null;
}): ExamType {
    return "national" in value ? ExamType.national : "university" in value ? ExamType.university : "state" in value ? ExamType.state : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ai: null;
} | {
    startup: null;
} | {
    core: null;
} | {
    general: null;
} | {
    robotics: null;
} | {
    webDev: null;
}): Domain {
    return "ai" in value ? Domain.ai : "startup" in value ? Domain.startup : "core" in value ? Domain.core : "general" in value ? Domain.general : "robotics" in value ? Domain.robotics : "webDev" in value ? Domain.webDev : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ai: null;
} | {
    roadmap: null;
} | {
    finance: null;
} | {
    startup: null;
} | {
    skills: null;
}): ResourceCategory {
    return "ai" in value ? ResourceCategory.ai : "roadmap" in value ? ResourceCategory.roadmap : "finance" in value ? ResourceCategory.finance : "startup" in value ? ResourceCategory.startup : "skills" in value ? ResourceCategory.skills : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idea: null;
} | {
    launch: null;
} | {
    scale: null;
} | {
    build: null;
} | {
    validation: null;
}): StartupStage {
    return "idea" in value ? StartupStage.idea : "launch" in value ? StartupStage.launch : "scale" in value ? StartupStage.scale : "build" in value ? StartupStage.build : "validation" in value ? StartupStage.validation : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    firstYear: null;
} | {
    workingProfessional: null;
} | {
    fourthYear: null;
} | {
    thirdYear: null;
} | {
    secondYear: null;
} | {
    aspirant: null;
}): UserStage {
    return "firstYear" in value ? UserStage.firstYear : "workingProfessional" in value ? UserStage.workingProfessional : "fourthYear" in value ? UserStage.fourthYear : "thirdYear" in value ? UserStage.thirdYear : "secondYear" in value ? UserStage.secondYear : "aspirant" in value ? UserStage.aspirant : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_College>): Array<College> {
    return value.map((x)=>from_candid_College_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EntranceExam>): Array<EntranceExam> {
    return value.map((x)=>from_candid_EntranceExam_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MentorProfile>): Array<MentorProfile> {
    return value.map((x)=>from_candid_MentorProfile_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StartupTip>): Array<StartupTip> {
    return value.map((x)=>from_candid_StartupTip_n44(_uploadFile, _downloadFile, x));
}
function to_candid_CollegeType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollegeType): _CollegeType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_College_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: College): _College {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Domain_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Domain): _Domain {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_EntranceExam_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntranceExam): _EntranceExam {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ExamType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamType): _ExamType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_MentorProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MentorProfile): _MentorProfile {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): _ResourceCategory {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Resource_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Resource): _Resource {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_StartupStage_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StartupStage): _StartupStage {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_StartupTip_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StartupTip): _StartupTip {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserStage_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStage): _UserStage {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    domain: Domain;
    yearsExperience: bigint;
    name: string;
    currentRole: string;
    college: string;
}): {
    id: bigint;
    bio: string;
    domain: _Domain;
    yearsExperience: bigint;
    name: string;
    currentRole: string;
    college: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        domain: to_candid_Domain_n11(_uploadFile, _downloadFile, value.domain),
        yearsExperience: value.yearsExperience,
        name: value.name,
        currentRole: value.currentRole,
        college: value.college
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    tags: Array<string>;
    author: string;
    category: ResourceCategory;
    contentSummary: string;
}): {
    id: bigint;
    title: string;
    tags: Array<string>;
    author: string;
    category: _ResourceCategory;
    contentSummary: string;
} {
    return {
        id: value.id,
        title: value.title,
        tags: value.tags,
        author: value.author,
        category: to_candid_ResourceCategory_n15(_uploadFile, _downloadFile, value.category),
        contentSummary: value.contentSummary
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    tags: Array<string>;
    stage: StartupStage;
}): {
    id: bigint;
    title: string;
    content: string;
    tags: Array<string>;
    stage: _StartupStage;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        tags: value.tags,
        stage: to_candid_StartupStage_n19(_uploadFile, _downloadFile, value.stage)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    collegeType: CollegeType;
    avgCutoff: bigint;
    establishedYear: bigint;
    state: string;
    nirfRanking: bigint;
    topBranches: Array<string>;
    location: string;
}): {
    id: bigint;
    name: string;
    collegeType: _CollegeType;
    avgCutoff: bigint;
    establishedYear: bigint;
    state: string;
    nirfRanking: bigint;
    topBranches: Array<string>;
    location: string;
} {
    return {
        id: value.id,
        name: value.name,
        collegeType: to_candid_CollegeType_n3(_uploadFile, _downloadFile, value.collegeType),
        avgCutoff: value.avgCutoff,
        establishedYear: value.establishedYear,
        state: value.state,
        nirfRanking: value.nirfRanking,
        topBranches: value.topBranches,
        location: value.location
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    applicationDeadline: bigint;
    conductingBody: string;
    websiteUrl: string;
    name: string;
    description: string;
    examDate: bigint;
    eligibilityCriteria: string;
    examType: ExamType;
}): {
    id: bigint;
    applicationDeadline: bigint;
    conductingBody: string;
    websiteUrl: string;
    name: string;
    description: string;
    examDate: bigint;
    eligibilityCriteria: string;
    examType: _ExamType;
} {
    return {
        id: value.id,
        applicationDeadline: value.applicationDeadline,
        conductingBody: value.conductingBody,
        websiteUrl: value.websiteUrl,
        name: value.name,
        description: value.description,
        examDate: value.examDate,
        eligibilityCriteria: value.eligibilityCriteria,
        examType: to_candid_ExamType_n7(_uploadFile, _downloadFile, value.examType)
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interests: Array<string>;
    name: string;
    stage: UserStage;
}): {
    interests: Array<string>;
    name: string;
    stage: _UserStage;
} {
    return {
        interests: value.interests,
        name: value.name,
        stage: to_candid_UserStage_n62(_uploadFile, _downloadFile, value.stage)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Domain): {
    ai: null;
} | {
    startup: null;
} | {
    core: null;
} | {
    general: null;
} | {
    robotics: null;
} | {
    webDev: null;
} {
    return value == Domain.ai ? {
        ai: null
    } : value == Domain.startup ? {
        startup: null
    } : value == Domain.core ? {
        core: null
    } : value == Domain.general ? {
        general: null
    } : value == Domain.robotics ? {
        robotics: null
    } : value == Domain.webDev ? {
        webDev: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): {
    ai: null;
} | {
    roadmap: null;
} | {
    finance: null;
} | {
    startup: null;
} | {
    skills: null;
} {
    return value == ResourceCategory.ai ? {
        ai: null
    } : value == ResourceCategory.roadmap ? {
        roadmap: null
    } : value == ResourceCategory.finance ? {
        finance: null
    } : value == ResourceCategory.startup ? {
        startup: null
    } : value == ResourceCategory.skills ? {
        skills: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StartupStage): {
    idea: null;
} | {
    launch: null;
} | {
    scale: null;
} | {
    build: null;
} | {
    validation: null;
} {
    return value == StartupStage.idea ? {
        idea: null
    } : value == StartupStage.launch ? {
        launch: null
    } : value == StartupStage.scale ? {
        scale: null
    } : value == StartupStage.build ? {
        build: null
    } : value == StartupStage.validation ? {
        validation: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollegeType): {
    iit: null;
} | {
    nit: null;
} | {
    iiit: null;
} | {
    privateCollege: null;
} | {
    deemed: null;
} {
    return value == CollegeType.iit ? {
        iit: null
    } : value == CollegeType.nit ? {
        nit: null
    } : value == CollegeType.iiit ? {
        iiit: null
    } : value == CollegeType.privateCollege ? {
        privateCollege: null
    } : value == CollegeType.deemed ? {
        deemed: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStage): {
    firstYear: null;
} | {
    workingProfessional: null;
} | {
    fourthYear: null;
} | {
    thirdYear: null;
} | {
    secondYear: null;
} | {
    aspirant: null;
} {
    return value == UserStage.firstYear ? {
        firstYear: null
    } : value == UserStage.workingProfessional ? {
        workingProfessional: null
    } : value == UserStage.fourthYear ? {
        fourthYear: null
    } : value == UserStage.thirdYear ? {
        thirdYear: null
    } : value == UserStage.secondYear ? {
        secondYear: null
    } : value == UserStage.aspirant ? {
        aspirant: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamType): {
    national: null;
} | {
    university: null;
} | {
    state: null;
} {
    return value == ExamType.national ? {
        national: null
    } : value == ExamType.university ? {
        university: null
    } : value == ExamType.state ? {
        state: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
